# Generated by Django 5.0.8 on 2024-08-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='destinataire_comptenum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
